### ISSUE TITLE
Lato font weight 

### ISSUE THREAD

**Issue by EncoreJackie** [EncoreMultimedia/hitech-testing#82]
The Lato font throughout the site needs to be Lato Normal 400, not Lato Light 300.  

http://encoredemo.com/design/hitech_dev/?num=2
![screen shot 2015-01-05 at 3 34 50 pm](https://cloud.githubusercontent.com/assets/5445121/5631005/8ec304dc-9588-11e4-830e-c54018b1afe0.png)

**Comment by chadsten** [comment]
Lato 400 doesn't exist for web.

http://screencloud.net/v/C6VN

**Comment by chadsten** [comment]
Bulk color change not possible since the variable usage is not very consistent. I'll need to change each value manually to ensure I'm not replacing background colors and stuff. 1990 lines and about 50 occurrences of the value, plus me checking to see where it is visually on site.
