### ISSUE TITLE
Job titles are cutting off

### ISSUE THREAD

**Issue by EncoreJackie** [EncoreMultimedia/hitech-testing#83]
Job titles are cutting off.
http://hitech.anakin.encoredemo.com/about/about-our-team

![screen shot 2015-01-07 at 3 31 32 pm](https://cloud.githubusercontent.com/assets/5445121/5653720/7474bc6a-9682-11e4-8eed-43c844bcad27.png)

**Comment by chadsten** [comment]
View updated.
