### ISSUE TITLE
Bullets aren't formatting correctly

### ISSUE THREAD

**Issue by EncoreJackie** [EncoreMultimedia/hitech-testing#84]
Bullets aren't formatting correctly

http://hitech-testing.stageserver.org/service/conventional-ndendt-methods/conventional-radiography-rt
![screen shot 2015-01-07 at 3 34 47 pm](https://cloud.githubusercontent.com/assets/5445121/5653768/c4bca6d8-9682-11e4-9e2f-36140af88458.png)

**Comment by chadsten** [comment]
Bulk change not possible since the variable usage is not very consistent. I'll need to change each value manually to ensure I'm not replacing background colors and stuff. 1990 lines and about 50 occurrences of the value, plus me checking to see where it is visually on site.

**Comment by EncoreJackie** [comment]
Bullets are lined up now, but I think the text is still a little larger and maybe darker?

**Comment by chadsten** [comment]
Fixed with #90
