### ISSUE TITLE
Last name cutting off on Locations

### ISSUE THREAD

**Issue by EncoreJackie** [EncoreMultimedia/hitech-testing#85]
The last name "Mehre" should be changed to "Mehrens". Is this a character limit thing? 
http://hitech.anakin.encoredemo.com/about/locations
![screen shot 2015-01-07 at 3 37 10 pm](https://cloud.githubusercontent.com/assets/5445121/5653809/24ac5084-9683-11e4-9388-91e66c070ec9.png)

**Comment by chadsten** [comment]
Fixed. The actual username was wrong, and this view actually looks AT the drupal user object.
