### ISSUE TITLE
Corporate contact link  

### ISSUE THREAD

**Issue by EncoreJackie** [EncoreMultimedia/hitech-testing#86]
Need to add green contact link for corporate office. 
Contact Shane Shankles >>  
shane.shankles@hitechtesting.com

These are somehow connected to the Careers. I'm guessing when we add it to the list, they will be able to choose Shane from the dropdown when adding a job listing also. 

http://hitech.anakin.encoredemo.com/about/locations
![screen shot 2015-01-07 at 3 56 01 pm](https://cloud.githubusercontent.com/assets/5445121/5654130/ea75bf38-9685-11e4-9bb1-f52dcafcdb53.png)

**Comment by chadsten** [comment]
User added to term.
