### ISSUE TITLE
News Archive

### ISSUE THREAD

**Issue by EncoreJackie** [EncoreMultimedia/hitech-testing#87]
http://hitech.anakin.encoredemo.com/news-archive

**Comment by EncoreJackie** [comment]
Can you remove 2012 from the archive?

**Comment by chadsten** [comment]
http://screencloud.net/v/80yt

Well, something is super broken.

**Comment by EncoreJackie** [comment]
Yes, that's what I was referring to originally. I somehow switched over to the stage link when I saw noticed the 2012 archive.

**Comment by chadsten** [comment]
The 2012 comes from that article that is dated for that. It will only show dates that contain content.
