### ISSUE TITLE
Video annotations/titles/bylines 

### ISSUE THREAD

**Issue by EncoreJackie** [EncoreMultimedia/hitech-testing#89]
Client is asking if we can remove the annotations/titles/bylines for the embedded Vimeo videos. 

"I tried adding "?title=0&byline=0&portrait=0" to the end of the video link on the "Careers" page but I think my &'s are being encoded."

**Comment by chadsten** [comment]
I have disabled everything available in the module's config. Let me know if there are still issues with this please.
